# Generated by Django 2.1.7 on 2019-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190418_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
