# Generated by Django 2.1.7 on 2019-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190418_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account',
            new_name='account_address',
        ),
    ]
