# Generated by Django 2.1.7 on 2019-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190419_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_bid',
            field=models.PositiveIntegerField(default=300000),
        ),
    ]
