# Generated by Django 2.1.7 on 2019-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_max_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='max_bid',
            new_name='budget',
        ),
    ]
