# Generated by Django 2.1.7 on 2019-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20190418_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
