# Generated by Django 2.1.7 on 2019-04-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_auto_20190419_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidland',
            old_name='value',
            new_name='price',
        ),
    ]
