# Generated by Django 2.1.7 on 2019-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20190419_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidland',
            name='days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bidland',
            name='token_money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
