# Generated by Django 2.1.7 on 2019-04-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_auto_20190425_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='land',
            new_name='bid_land',
        ),
    ]
