# Generated by Django 2.1.7 on 2019-04-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_bid_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidland',
            old_name='active',
            new_name='locked',
        ),
    ]
